# Generated by Django 4.1.13 on 2023-12-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0003_remove_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
