# Generated by Django 4.1.13 on 2023-12-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApps', '0002_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
